// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SimpleVehicle","status":true,"description":"v1.2 Allows you to drive/ride a vehicle on land.","parameters":{"Vehicle Speed":"5","Encounters":"false","Touch Events":"false","Action Button Events":"false","Forbid Region ID":"1"}},
{"name":"YEP_EventSpawner","status":true,"description":"v1.02 Spawn premade events at specific locations or random\npoints marked by regions.","parameters":{"---General---":"","TemplateMaps":"[\"3\"]","TemplateNames":"[\"{\\\"Name\\\":\\\"Chair\\\",\\\"MapID\\\":\\\"10\\\",\\\"EventID\\\":\\\"1\\\"}\",\"{\\\"Name\\\":\\\"Music Box\\\",\\\"MapID\\\":\\\"10\\\",\\\"EventID\\\":\\\"2\\\"}\",\"{\\\"Name\\\":\\\"Statue\\\",\\\"MapID\\\":\\\"10\\\",\\\"EventID\\\":\\\"3\\\"}\"]","IdStartRange":"1000"}}
];
